### ISSUE TITLE
_vueAuthenticate.VueAuthenticate is not a constructor

### ISSUE THREAD

**Issue by oseintow** [dgrubelic/vue-authenticate#156]
Not able to run my test becuase of the following error. 

```
    TypeError: _vueAuthenticate.VueAuthenticate is not a constructor

      Vue.use(VueAxios, axios)

     const vueAuth = new VueAuthenticate(Vue.prototype.$http, {
                                 ^
      baseUrl: 'http://localhost:8000',

      providers: {

      at Object.<anonymous> (resources/js/store/modules/auth.js:10:17)
      at Object.<anonymous> (resources/js/store/modules/__tests__/auth.spec.js:5:1)
```

What am i doing wrong. It works well in browser but for test it give me the error above

**Comment by gurupras** [comment]
@oseintow Have you found a fix for this? I'm running into the same issue and I don't know how to fix it.

**Comment by tony-kappen-red-oak** [comment]
I was able to get around this issue by doing this:
```
const vueAuth =  VueAuthenticate.factory(Vue.prototype.$http, {})
```

**Comment by shonkhor22** [comment]
How am I fix this error,
VueAuthenticate is not a constructor
![image](https://user-images.githubusercontent.com/85008025/131226208-e735e475-46ac-40e5-bb21-21098277efc6.png)
, please answel me

**Comment by erdalonline** [comment]
> How am I fix this error,
> VueAuthenticate is not a constructor
> ![image](https://user-images.githubusercontent.com/85008025/131226208-e735e475-46ac-40e5-bb21-21098277efc6.png)
> , please answel me

I'm having the same problem.
